global:
  checkNewVersion: false
  sendAnonymousUsage: false

accessLog:
  filePath: /home/cloud-user/traefik/access.log

log:
  level: DEBUG
  filePath: /home/cloud-user/traefik/traefik.log

api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ':443'

serversTransport:
  insecureSkipVerify: true

providers:
  file:
    filename: /home/cloud-user/traefik/config.yml
    watch: true
